version: '3.8'

services:
  redmine:
    image: redmine:latest
    container_name: redmine
    ports:
      - "3000:3000"
    volumes:
      - redmine_data:/usr/src/redmine/files
    environment:
      - REDMINE_DB_HOST=db
      - REDMINE_DB_DATABASE=redmine
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_DB_PASSWORD=redmine_pass@1
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: redmine_db
    environment:
      MYSQL_ROOT_PASSWORD: root_pass@1
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine_pass@1
    volumes:
      - db_data:/var/lib/mysql

volumes:
  redmine_data:
  db_data:
